// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0
// source: entries.sql

package db

import (
	"context"
	"database/sql"
)

const createEntry = `-- name: CreateEntry :execresult
INSERT INTO entries (
    account_id,
    amount
) VALUES (
             ?,?
         )
`

type CreateEntryParams struct {
	AccountID sql.NullInt64
	Amount    float64
}

func (q *Queries) CreateEntry(ctx context.Context, arg CreateEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createEntry, arg.AccountID, arg.Amount)
}
