// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"database/sql"
	"time"
)

type Account struct {
	ID int64
	// must be positive
	Balance   float64
	CreatedAt time.Time
}

type Entry struct {
	ID        int64
	AccountID sql.NullInt64
	// can be negative and positive
	Amount    float64
	CreatedAt time.Time
}

type Transfer struct {
	ID            int64
	FromAccountID sql.NullInt64
	ToAccountID   sql.NullInt64
	Amount        float64
	CreatedAt     time.Time
}
