// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) (sql.Result, error)
	CreateEntry(ctx context.Context, arg CreateEntryParams) (sql.Result, error)
	CreateTransfer(ctx context.Context, arg CreateTransferParams) (sql.Result, error)
	GetAccount(ctx context.Context, id int64) (GetAccountRow, error)
	GetAccountForBalanceUpdate(ctx context.Context, arg GetAccountForBalanceUpdateParams) (int64, error)
	GetAccountForUpdate(ctx context.Context, id int64) (int64, error)
	//
	UpdateBalance(ctx context.Context, arg UpdateBalanceParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
